<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InvariantGlobalization>true</InvariantGlobalization>
<!--        <InvariantGlobalization>false</InvariantGlobalization>-->
<!--        <WasmIncludeFullIcuData>true</WasmIncludeFullIcuData>-->
<!--        <WasmIcuDataFileName>icudt.dat</WasmIcuDataFileName>-->
<!--        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>-->
        
<!--        <BlazorWebAssemblyJiterpreter>false</BlazorWebAssemblyJiterpreter>-->
<!--        <WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>-->
        
<!--        <RunAOTCompilation>true</RunAOTCompilation>-->
<!--        <RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>-->
<!--        <WasmNativeStrip>false</WasmNativeStrip>-->
<!--        <WasmProfilers>browser;</WasmProfilers>-->
<!--        <WasmBuildNative>true</WasmBuildNative>-->

<!--        <EmccExtraCFlags>-s MAIN_MODULE=2 -sAUTOLOAD_DYLIBS=0</EmccExtraCFlags>-->
<!--        <EmccExtraCFlags>-s SHARED_MEMORY=1</EmccExtraCFlags>-->
<!--        <EmccExtraLDFlags>-s SHARED_MEMORY=1</EmccExtraLDFlags>-->
        
<!--        <WasmEnableThreads>true</WasmEnableThreads>-->
        <SkiaUseGraphite>True</SkiaUseGraphite>
        <WasmEnableSIMD>True</WasmEnableSIMD>
        <WasmAllowUndefinedSymbols>True</WasmAllowUndefinedSymbols>
        <EmccInitialHeapSize>128MB</EmccInitialHeapSize>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    </ItemGroup>
    
    <Import Project="../PixUI.Drawing.Skia/Native/Wasm.targets" />
    
    <ItemGroup>
        <ProjectReference Include="..\PixUI.Demo\PixUI.Demo.csproj" />
        <ProjectReference Include="..\PixUI.Drawing.Skia\PixUI.Drawing.Skia.csproj" />
        <ProjectReference Include="..\PixUI\PixUI.csproj" />
    </ItemGroup>

</Project>
