<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(DefineConstants);SKIA_IMAGE_LVC;</DefineConstants>
    </PropertyGroup>

    <Import Project="..\..\ext\LiveCharts2\src\skiasharp\_Shared\_Shared.projitems" Label="Shared" />

    <ItemGroup>
      <ProjectReference Include="..\..\ext\LiveCharts2\src\LiveChartsCore\LiveChartsCore.csproj" />
      <ProjectReference Include="..\PixUI\PixUI.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ext\LiveCharts2\generators\LiveChartsGenerators\LiveChartsGenerators.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="TypeConverters\" />
    </ItemGroup>

</Project>
