<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefineConstants>$(DefineConstants);USE_LIBRARY_IMPORT</DefineConstants>
        <SkiaUseGraphite>False</SkiaUseGraphite>
        <DefineConstants Condition="'$(SkiaUseGraphite)' == 'True'">$(DefineConstants);SK_GRAPHITE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PixUI.Drawing\PixUI.Drawing.csproj"/>
    </ItemGroup>

</Project>
